<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/25
 * Time: 15:52
 */
namespace backend\models;

use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends ActiveRecord implements IdentityInterface {
    public $password;
    public $apassword;
    public $bpassword;
    public $cpassword;
    public $Roles= [];
    const SCENARIO_ADD='add';
    const SCENARIO_PERSONAL='Personal';

    public static $status =[
        '10'=>'正常','0'=>'禁用'
    ];
    public function rules()
    {
        return [
            ['Roles','safe'],
            [['username','password'],'required','on'=>self::SCENARIO_ADD],
             ['email','safe'],
            ['username','unique'],
            [['apassword','bpassword','cpassword'],'required','on'=>self::SCENARIO_PERSONAL],
            ['cpassword','compare','compareAttribute'=>'bpassword','message'=>'两次密码必须一致','on'=>self::SCENARIO_PERSONAL],

        ];
    }

    public function attributeLabels()
    {
        return [
          'username'=>'用户名',
            'password'=>'密码',
            'email'=>'邮箱',
            'apassword'=>'旧密码',
            'bpassword'=>'新密码',
            'cpassword'=>'确认新密码',
            'Roles'=>'添加角色'
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->password_hash=\Yii::$app->security->generatePasswordHash($this->password);
            $this->status = 10;
            $this->created_at = time();
            $this->auth_key = \Yii::$app->security->generateRandomString();
        }else{
            if($this->password){
                $this->password_hash = \Yii::$app->security->generatePasswordHash($this->password);
                $this->updated_at = time();
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Finds an identity by the given ID.
     * @param string|int $id the ID to be looked for
     * @return IdentityInterface the identity object that matches the given ID.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentity($id)
    {
        return self::findOne(['id'=>$id]);
        // TODO: Implement findIdentity() method.
    }

    /**
     * Finds an identity by the given token.
     * @param mixed $token the token to be looked for
     * @param mixed $type the type of the token. The value of this parameter depends on the implementation.
     * For example, [[\yii\filters\auth\HttpBearerAuth]] will set this parameter to be `yii\filters\auth\HttpBearerAuth`.
     * @return IdentityInterface the identity object that matches the given token.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    /**
     * Returns an ID that can uniquely identify a user identity.
     * @return string|int an ID that uniquely identifies a user identity.
     */
    public function getId()
    {
        return $this->id;
        // TODO: Implement getId() method.
    }

    /**
     * Returns a key that can be used to check the validity of a given identity ID.
     *
     * The key should be unique for each individual user, and should be persistent
     * so that it can be used to check the validity of the user identity.
     *
     * The space of such keys should be big enough to defeat potential identity attacks.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @return string a key that is used to check the validity of a given identity ID.
     * @see validateAuthKey()
     */
    public function getAuthKey()
    {
        return $this->auth_key;
        // TODO: Implement getAuthKey() method.
    }

    /**
     * Validates the given auth key.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @param string $authKey the given auth key
     * @return bool whether the given auth key is valid.
     * @see getAuthKey()
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey()==$authKey;
        // TODO: Implement validateAuthKey() method.
    }
}